### ISSUE TITLE
Bug: `recmf` accepts repeated flags

### ISSUE THREAD

**Issue by le0tan** [AY1920S1-CS2103-T16-1/main#199]
Command: `recmf -f -f`

You may either write in UG that duplicate flags will be considered as one or prohibit such behavior.

![image](https://user-images.githubusercontent.com/28982486/68386781-bd8c4f00-0197-11ea-9cee-c8b36e8d7e90.png)

**Comment by ZhangHuafan** [comment]
This is already specified in UG. Please read carefully.
